#!/usr/bin/env bash
# Native YuE2 text-to-music runtime for Local Dream.
#
# YuE2 uses a dedicated, pinned Hexagon DSPQueue backend. The previous JZ
# single-mempool transport could reserve ~4 GiB on the Android side but then
# fail when the SM8850 DSP process tried to map that same region. DSPQueue uses
# normal per-buffer mappings instead of one giant shared VA reservation, so it
# avoids that failure mode without source patches or CPU compatibility paths.
#
# The backend is built directly from one reviewed upstream commit. Local Dream
# does not rewrite ggml-hexagon source and ships the matching AP/DSP binaries.
set -euo pipefail

: "${ANDROID_NDK_ROOT:?set ANDROID_NDK_ROOT}"
: "${HEXAGON_SDK_ROOT:?set HEXAGON_SDK_ROOT}"

cd "$(dirname "$0")"
BUILD_DIR=build/android
YUE2_DIR="$(cd ../3rdparty/yue2.cpp && pwd)"

JZ_REPO="https://github.com/kan-linux/ggml-hexagon.git"
JZ_COMMIT="2b129ccfa03aea330d2d9ac4650a10de393dbe3a"
JZ_ROOT="$(pwd)/build/deps/ggml-hexagon"
GGML_DIR="$JZ_ROOT/ggml"

# Fetch exactly one reviewed backend revision. This is a normal pinned
# dependency, not a source rewrite/monkey patch.
if [[ ! -d "$JZ_ROOT/.git" ]]; then
    rm -rf "$JZ_ROOT"
    mkdir -p "$(dirname "$JZ_ROOT")"
    git init -q "$JZ_ROOT"
    git -C "$JZ_ROOT" remote add origin "$JZ_REPO"
fi

if [[ "$(git -C "$JZ_ROOT" rev-parse HEAD 2>/dev/null || true)" != "$JZ_COMMIT" ]]; then
    git -C "$JZ_ROOT" fetch -q --depth 1 origin "$JZ_COMMIT"
    git -C "$JZ_ROOT" checkout -q --detach FETCH_HEAD
fi

test "$(git -C "$JZ_ROOT" rev-parse HEAD)" = "$JZ_COMMIT"
test -f "$GGML_DIR/CMakeLists.txt"

# Start from the exact upstream tree every time. No Local Dream patchset is
# applied here; any backend fix must exist in the pinned backend revision.
git -C "$JZ_ROOT" reset --hard "$JZ_COMMIT"
git -C "$JZ_ROOT" clean -fdx
test -f "$GGML_DIR/src/ggml-hexagon/ggml-hexagon.cpp"
grep -q '#include <dspqueue.h>' "$GGML_DIR/src/ggml-hexagon/ggml-hexagon.cpp"

rm -rf "$BUILD_DIR"

cmake -S "$YUE2_DIR" -B "$BUILD_DIR" -G Ninja \
    -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake" \
    -DANDROID_ABI=arm64-v8a \
    -DANDROID_PLATFORM=android-28 \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_PROJECT_INCLUDE="$(pwd)/android-yue2-deps.cmake" \
    -DCMAKE_C_FLAGS="-march=armv8.7a+fp16+dotprod+i8mm -D_GNU_SOURCE" \
    -DCMAKE_CXX_FLAGS="-march=armv8.7a+fp16+dotprod+i8mm -D_GNU_SOURCE" \
    -DGGML_SOURCE_DIR="$GGML_DIR" \
    -DGGML_HEXAGON=ON \
    -DGGML_OPENMP=OFF \
    -DGGML_LLAMAFILE=OFF \
    -DGGML_BACKEND_DL=OFF \
    -DPREBUILT_LIB_DIR=android_aarch64 \
    -DBUILD_SHARED_LIBS=OFF \
    -DBUILD_TESTING=OFF \
    -DHEXAGON_SDK_ROOT="$HEXAGON_SDK_ROOT" \
    -DCMAKE_POLICY_VERSION_MINIMUM=3.10

# ExternalProject skels are not guaranteed to be pulled in by the host
# executable target, so build the two Android architectures Local Dream ships
# explicitly. This is still one matched source/backend revision.
cmake --build "$BUILD_DIR" --target yue-server htp-v79 htp-v81 -j "$(nproc)"

JNI_DIR="$(cd ../.. && pwd)/jniLibs/arm64-v8a"
ASSET_DIR="$(cd ../.. && pwd)/assets/yue2libs"
mkdir -p "$JNI_DIR" "$ASSET_DIR"

cp "$BUILD_DIR/yue-server" "$JNI_DIR/libyue2_server.so"

# Keep YuE2's DSPQueue skels in their own asset directory so image-generation
# runtimes can continue using their independently-built Hexagon runtime without
# binary collisions.
for arch in v79 v81; do
    skel="$(find "$BUILD_DIR" -type f -name "libggml-htp-${arch}.so" -print -quit)"
    if [[ -z "$skel" || ! -s "$skel" ]]; then
        echo "Missing YuE2 mempool HTP skel for $arch" >&2
        exit 1
    fi
    cp "$skel" "$ASSET_DIR/libggml-htp-${arch}.so"
done

# DSPQueue is configured via GGML_HEXAGON_* environment variables. Remove any
# stale mempool config generated by an older native build.
rm -f "$ASSET_DIR/ggml-hexagon.cfg"

cat > "$ASSET_DIR/backend-version.txt" <<EOF
backend=kan-linux/ggml-hexagon
commit=$JZ_COMMIT
variant=dspqueue
patchset=none
EOF

chmod +x "$JNI_DIR/libyue2_server.so"
ls -lh "$JNI_DIR/libyue2_server.so" "$ASSET_DIR"/libggml-htp-v{79,81}.so
